fix: fix .d.ts paths in package

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -42,6 +42,13 @@ Build:
     - npm run --if-present build
     - npm pack
     - npm exec npm-pkg-lint
+    - |
+      for dts in dist/{cjs,es}/{index,browser,jest,test-utils}.d.ts; do
+        if [[ ! -e "${dts}" ]]; then
+          echo "${dts}" is missing from package
+          exit 1
+        fi
+      done
 
 pages:
   stage: build
